/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.ferramentas.BaldeDeTinta;
import gui.geom.Caneta;
import gui.geom.Elipse;
import gui.geom.Forma;
import gui.geom.Linha;
import gui.geom.Poligono;
import gui.geom.Retangulo;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger( JanelaPrincipal.class.getName() );
    
    private Forma novaForma;
    private int quantidadeLados;
    private int ultimoApagarX;
    private int ultimoApagarY;

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        quantidadeLados = 3;
        
        java.awt.event.ActionListener cursorListener = e -> atualizarCursor();
        Borracha.addActionListener(cursorListener);
        btnBalde.addActionListener(cursorListener);
        btnLinha.addActionListener(cursorListener);
        btnRetangulo.addActionListener(cursorListener);
        btnElipse.addActionListener(cursorListener);
        btnPoligono.addActionListener(cursorListener);
        btnCaneta.addActionListener(cursorListener);
    }
    
    private void atualizarCursor() {
        if (Borracha.isSelected()) {
            java.awt.Dimension bestSize = java.awt.Toolkit.getDefaultToolkit().getBestCursorSize(12, 12);
            int cursorWidth = Math.max(bestSize.width, 12);
            int cursorHeight = Math.max(bestSize.height, 12);

            java.awt.image.BufferedImage img = new java.awt.image.BufferedImage(cursorWidth, cursorHeight, java.awt.image.BufferedImage.TYPE_INT_ARGB);
            java.awt.Graphics2D g = img.createGraphics();
            
            int startX = (cursorWidth - 12) / 2;
            int startY = (cursorHeight - 12) / 2;

            g.setColor(java.awt.Color.WHITE);
            g.fillRect(startX, startY, 12, 12);
            g.setColor(java.awt.Color.BLACK);
            g.drawRect(startX, startY, 11, 11);
            g.dispose();
            
            java.awt.Cursor cursorBorracha = java.awt.Toolkit.getDefaultToolkit().createCustomCursor(
                    img, new java.awt.Point(startX + 6, startY + 6), "CursorBorracha");
            painelDesenho.setCursor(cursorBorracha);
        } else {
            painelDesenho.setCursor(java.awt.Cursor.getDefaultCursor());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFerramentas = new javax.swing.ButtonGroup();
        DesfazerRefazer = new javax.swing.ButtonGroup();
        painelDesenho = new gui.PainelDesenho();
        painelFerramentas = new javax.swing.JPanel();
        Borracha = new javax.swing.JToggleButton();
        btnBalde = new javax.swing.JToggleButton();
        btnLinha = new javax.swing.JToggleButton();
        btnRetangulo = new javax.swing.JToggleButton();
        btnElipse = new javax.swing.JToggleButton();
        btnPoligono = new javax.swing.JToggleButton();
        btnCaneta = new javax.swing.JToggleButton();
        painelCorContorno = new javax.swing.JPanel();
        painelCorPreenchimento = new javax.swing.JPanel();
        Desfazer = new javax.swing.JButton();
        Refazer = new javax.swing.JButton();
        btnPixelArt = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu Paint");

        painelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseDragged(evt);
            }
        });
        painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelDesenhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        btnGroupFerramentas.add(Borracha);
        Borracha.setText("Borracha");
        Borracha.addActionListener(this::BorrachaActionPerformed);

        btnGroupFerramentas.add(btnBalde);
        btnBalde.setText("Balde");
        btnBalde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBalde.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnLinha);
        btnLinha.setSelected(true);
        btnLinha.setText("Linha");
        btnLinha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLinha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnRetangulo);
        btnRetangulo.setText("Retângulo");
        btnRetangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnElipse);
        btnElipse.setText("Elipse");
        btnElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnElipse.addActionListener(this::btnElipseActionPerformed);

        btnGroupFerramentas.add(btnPoligono);
        btnPoligono.setText("Polígono");
        btnPoligono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPoligono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPoligono.addActionListener(this::btnPoligonoActionPerformed);

        btnGroupFerramentas.add(btnCaneta);
        btnCaneta.setText("Caneta");
        btnCaneta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaneta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCaneta.addActionListener(this::btnCanetaActionPerformed);

        painelCorContorno.setBackground(new java.awt.Color(0, 0, 0));
        painelCorContorno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelCorContorno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelCorContorno.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorContorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorContornoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorContornoLayout = new javax.swing.GroupLayout(painelCorContorno);
        painelCorContorno.setLayout(painelCorContornoLayout);
        painelCorContornoLayout.setHorizontalGroup(
            painelCorContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelCorContornoLayout.setVerticalGroup(
            painelCorContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        painelCorPreenchimento.setBackground(new java.awt.Color(255, 255, 255));
        painelCorPreenchimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelCorPreenchimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelCorPreenchimento.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorPreenchimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorPreenchimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorPreenchimentoLayout = new javax.swing.GroupLayout(painelCorPreenchimento);
        painelCorPreenchimento.setLayout(painelCorPreenchimentoLayout);
        painelCorPreenchimentoLayout.setHorizontalGroup(
            painelCorPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelCorPreenchimentoLayout.setVerticalGroup(
            painelCorPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        Desfazer.setText("Desfazer");
        DesfazerRefazer.add(Desfazer);
        Desfazer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesfazerMouseClicked(evt);
            }
        });
        Desfazer.addActionListener(this::DesfazerActionPerformed);

        Refazer.setText("Refazer");
        DesfazerRefazer.add(Refazer);
        Refazer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefazerMouseClicked(evt);
            }
        });

        btnGroupFerramentas.add(btnPixelArt);
        btnPixelArt.setText("Pixel Art");
        btnPixelArt.addActionListener(this::btnPixelArtActionPerformed);

        javax.swing.GroupLayout painelFerramentasLayout = new javax.swing.GroupLayout(painelFerramentas);
        painelFerramentas.setLayout(painelFerramentasLayout);
        painelFerramentasLayout.setHorizontalGroup(
            painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnElipse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPoligono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCaneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBalde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPixelArt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Borracha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(Desfazer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refazer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelFerramentasLayout.setVerticalGroup(
            painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelFerramentasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelCorPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPoligono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnElipse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRetangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Desfazer)
                        .addComponent(Refazer))
                    .addComponent(painelCorContorno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPixelArt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(Borracha))
                    .addComponent(btnBalde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCaneta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painelDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMousePressed
        if (btnBalde.isSelected()) {
            BaldeDeTinta.preencher(painelDesenho, evt.getX(), evt.getY(), painelCorPreenchimento.getBackground());
            novaForma = null;
            return;
        }
        
        if (Borracha.isSelected()) {
            painelDesenho.salvarEstado(); 
            ultimoApagarX = evt.getX();
            ultimoApagarY = evt.getY();
            painelDesenho.apagar(ultimoApagarX, ultimoApagarY, evt.getX(), evt.getY());
            novaForma = null; 
            return; 
        }

        if (btnPixelArt.isSelected() || painelDesenho.getGradePixelArt().isVisivel()) {
            painelDesenho.salvarEstado();
            painelDesenho.pintarPixel(evt.getX(), evt.getY(), painelCorContorno.getBackground());
            novaForma = null;
            return;
        }
        
        painelDesenho.salvarEstado();

        if (btnLinha.isSelected()) {
            novaForma = new Linha();
        } else if (btnRetangulo.isSelected()) {
            novaForma = new Retangulo();
        } else if (btnElipse.isSelected()) {
            novaForma = new Elipse();
        } else if (btnPoligono.isSelected()) {
            novaForma = new Poligono(quantidadeLados);
        } else if (btnCaneta.isSelected()) {
            novaForma = new Caneta();
        } else {
            novaForma = new Linha();
        }

        if (novaForma instanceof Caneta) {
            ((Caneta) novaForma).adicionarPonto(evt.getX(), evt.getY());
        }

        novaForma.setIniX(evt.getX());
        novaForma.setIniY(evt.getY());
        novaForma.setFimX(evt.getX());
        novaForma.setFimY(evt.getY());
        novaForma.setCorContorno(painelCorContorno.getBackground());
        novaForma.setCorPreenchimento(painelCorPreenchimento.getBackground());

        painelDesenho.adicionarForma(novaForma);
    }//GEN-LAST:event_painelDesenhoMousePressed

    private void painelDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseReleased
        if (btnPixelArt.isSelected() || painelDesenho.getGradePixelArt().isVisivel()) {
            painelDesenho.pintarPixel(evt.getX(), evt.getY(), painelCorContorno.getBackground());
            return;
        }

        if (novaForma == null) return;

        if (novaForma instanceof Caneta) {
            ((Caneta) novaForma).adicionarPonto(evt.getX(), evt.getY());
        } else {
            novaForma.setFimX(evt.getX());
            novaForma.setFimY(evt.getY());
        }
        painelDesenho.repaint();
    }//GEN-LAST:event_painelDesenhoMouseReleased

    private void painelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseDragged
        
        if (Borracha.isSelected()) {
            painelDesenho.apagar(ultimoApagarX, ultimoApagarY, evt.getX(), evt.getY());
            ultimoApagarX = evt.getX();
            ultimoApagarY = evt.getY();
            return; 
        }
            
        if (painelDesenho.getGradePixelArt().isVisivel()) {
            painelDesenho.pintarPixel(evt.getX(), evt.getY(), painelCorContorno.getBackground());
            return;
        }
        
        if (novaForma == null) return;
        
        if (novaForma instanceof Caneta) {
            ((Caneta) novaForma).adicionarPonto(evt.getX(), evt.getY());
        } else {
            novaForma.setFimX(evt.getX());
            novaForma.setFimY(evt.getY());
        }
        painelDesenho.repaint();
    }//GEN-LAST:event_painelDesenhoMouseDragged

    private void painelCorContornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorContornoMouseClicked
        
        Color corSelecionada = JColorChooser.showDialog( 
                this, "Cor do Contorno", painelCorContorno.getBackground() );
        
        if ( corSelecionada != null ) {
            painelCorContorno.setBackground( corSelecionada );
        }
        
    }//GEN-LAST:event_painelCorContornoMouseClicked

    private void painelCorPreenchimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorPreenchimentoMouseClicked
        
        Color corSelecionada = JColorChooser.showDialog( 
                this, "Cor do Preenchimento", painelCorPreenchimento.getBackground() );
        
        if ( corSelecionada != null ) {
            painelCorPreenchimento.setBackground( corSelecionada );
        }
        
    }//GEN-LAST:event_painelCorPreenchimentoMouseClicked

    private void btnPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoligonoActionPerformed

        
        try{
            String valor = JOptionPane.showInputDialog("Quantidade de Lados");
            int quantidade = Integer.parseInt(valor);
            if( quantidadeLados < 3){
                quantidadeLados = 3;
            }
            
            quantidadeLados = quantidade;
            
        }catch(NumberFormatException exc){
        }
    }//GEN-LAST:event_btnPoligonoActionPerformed

    private void btnCanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCanetaActionPerformed

    private void btnElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElipseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElipseActionPerformed

    private void DesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesfazerActionPerformed

    }//GEN-LAST:event_DesfazerActionPerformed

    private void DesfazerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesfazerMouseClicked
        painelDesenho.desfazer();
    }//GEN-LAST:event_DesfazerMouseClicked

    private void RefazerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefazerMouseClicked
        painelDesenho.refazer();
    }//GEN-LAST:event_RefazerMouseClicked

    private void btnPixelArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPixelArtActionPerformed
        boolean ativo = !painelDesenho.getGradePixelArt().isVisivel();
        painelDesenho.getGradePixelArt().setVisivel(ativo);

        if (ativo) {
            String input = JOptionPane.showInputDialog(this, "Informe o número de pixels (ex: 8, 16, 32, 64):", "32");
            try {
                int res = Integer.parseInt(input);
                if (res > 0) {
                    painelDesenho.getGradePixelArt().redimensionar(res, res);
            }
            } catch (NumberFormatException exc) {
                // Mantém resolução anterior caso digite inválido
            }
        }
        painelDesenho.repaint();
    }//GEN-LAST:event_btnPixelArtActionPerformed

    private void BorrachaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrachaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrachaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex ) {
            logger.log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( () -> new JanelaPrincipal().setVisible( true ) );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Borracha;
    private javax.swing.JButton Desfazer;
    private javax.swing.ButtonGroup DesfazerRefazer;
    private javax.swing.JButton Refazer;
    private javax.swing.JToggleButton btnBalde;
    private javax.swing.JToggleButton btnCaneta;
    private javax.swing.JToggleButton btnElipse;
    private javax.swing.ButtonGroup btnGroupFerramentas;
    private javax.swing.JToggleButton btnLinha;
    private javax.swing.JToggleButton btnPixelArt;
    private javax.swing.JToggleButton btnPoligono;
    private javax.swing.JToggleButton btnRetangulo;
    private javax.swing.JPanel painelCorContorno;
    private javax.swing.JPanel painelCorPreenchimento;
    private gui.PainelDesenho painelDesenho;
    private javax.swing.JPanel painelFerramentas;
    // End of variables declaration//GEN-END:variables
}
